name: Python CI RankingPage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11, 3.12]  # Die nicht unterstützte 3.1-Version wurde entfernt
        os: [ubuntu-latest, windows-latest, macos-latest]



    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Holt den Code aus dem Repository

    - name: Set up Python
      uses: actions/setup-python@v4  # Richtet die angegebene Python-Version ein
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Installiere die Abhängigkeiten aus der requirements.txt

    - name: Run tests
      run: |
        pytest  # Führe die Tests mit pytest aus